# Generated by Django 3.0.3 on 2020-05-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('empCode', models.CharField(max_length=3)),
                ('mobileNo', models.CharField(max_length=255)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee_register.Position')),
            ],
        ),
    ]
